version: '3.8'

services:
  202412345-web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - 202412345-db
    environment:
      - DB_HOST=202412345-db
      - DB_NAME=202412345_shareride_db
      - DB_USER=root
      - DB_PASS=password

  202412345-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 202412345_shareride_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  202412345-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 202412345-db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - 202412345-db

volumes:
  db_data: